### ISSUE TITLE
Documentation: 404 error for "Customizing emails"

### ISSUE THREAD

**Issue by Sammeeey** [ajharry69/django-rest-xauth#41]
clicking "Customizing emails" on the [Docs](https://django-rest-xauth.readthedocs.io/en/latest/about/contributing/)
![grafik](https://user-images.githubusercontent.com/49591562/156780583-169c7cee-3c5a-4675-967d-38f8a2fe768f.png)

...
results in:
![grafik](https://user-images.githubusercontent.com/49591562/156780740-f1408ee6-c834-4ef9-8dba-0c65c440df86.png)

**Comment by ajharry69** [comment]
@Sammeeey, sorry for the inconvenience (once again). For now (before the doc is updated), you should be able to achieve **email customization** by doing the following (here I'll use [email-request-verification](https://github.com/ajharry69/django-rest-xauth/blob/master/xauth/templates/xauth/email-request-verification.html) as an example):

1. From your repository's root directory, create a file (with the same name and extension) as the one you'd like to override in the `templates/xauth/` directory. For example, `templates/xauth/email-request-verification.html`. Then re-write according to your preference. **As you re-write the `*.html` copy of the email, do not forget to do the same to the `*.txt` alternative**.

**N/B:** Make sure you've updated `settings.TEMPLATES[...]["DIRS"]` to include `templates`.

The following is a table of `context` passed to the relevant templates.
| Template name | Context |
| ------ | ------- |
| `email-request-verification.(html/txt)` | `{"code": "<generated verification code>", "user" : "<get_user_model() instance>", "app_name": settings.XAUTH_EMAIL_APP_NAME, "subject": settings.XAUTH_VERIFICATION_REQUEST_SUBJECT}` |
| `email-request-password-reset.(html/txt)` | `{"password": "generated temporary password", "user" : "<get_user_model() instance>", "app_name": settings.XAUTH_EMAIL_APP_NAME, "subject": settings.XAUTH_PASSWORD_RESET_REQUEST_SUBJECT}` |

**Comment by Sammeeey** [comment]
Thank you for the manual.
I've actually created the issue here and in #42 and #43 to motivate people contributing to your repo with "good first issues"

**Comment by ajharry69** [comment]
Updated the docs to remove the links returning 404.
