### ISSUE TITLE
Documentation: 404 error for "Endpoints"

### ISSUE THREAD

**Issue by Sammeeey** [ajharry69/django-rest-xauth#43]
- similar to #41 for the *Endpoints* link in the sidebar

**Comment by ajharry69** [comment]
@Sammeeey, sorry for the inconvenience. Due to time constraints, I haven't really been able to update the docs. For now, in order to see the endpoints, you can clone the repo then start up the test server following the [README](https://github.com/ajharry69/django-rest-xauth#test-run).

**Comment by ajharry69** [comment]
Updated the docs to remove the links returning 404.
